name: 'build-test'
on:
  schedule:
    - cron: "30 11 * * *" # 北京时间上午06:30
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ServerChan · Server酱通知
        uses: easychen/github-action-server-chan@v1.0.0
        with:
          sendkey: ${{ secrets.sendkey }}
          title: "运动步数通知，应该成功了吧？??"
